Changes for quiz
insper-education/active-handout-plugins-py pull request #49
Opened 2022-12-28 15:15 UTC by igordsm

Code to receive quiz results and return last answer. Includes options to show/hide answers and reset button, count and seed values in templating and backend code to mark a TelemetryData as the last answer.

2022-12-28 17:07 UTC, toshikurauchi requested changes
Acho que a dúvida principal é sobre a atualização do `last` que me pareceu redundante com o signal.

2022-12-28 17:07 UTC, toshikurauchi commented on src/active_handout_plugins/exercise.py
> +                self.id = f'{c[3:]}_{self.counter}'
Será que sempre queremos isso? Se eu só trocar um exercício de múltipla escolha de ordem, não deveria manter o id (caso eu tivesse definido um id fixo)?

2022-12-29 00:28 UTC, igordsm commented
Fiz tudo aqui. Acho que agora está OK :)

2022-12-29 12:59 UTC, toshikurauchi approved these changes

2022-12-29 12:59 UTC, merged